### ISSUE TITLE
Error in running the demo site

### ISSUE THREAD

**Issue by erasmodanarni** [shacker/gtd#1]
Hello. After having installed the dependencies with `pipenv install` I get the following error. Any ideas on how to proceed and about the reason of the error? Many thanks.

```
./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10bfbd620>
Traceback (most recent call last):
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/maurizio/.virtualenvs/gtd-VJmtv4Z6/lib/python3.6/site-packages/todo/__init__.py", line 67
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax
```

**Comment by shacker** [comment]
@erasmodanarni Wow, that's a weird one - no useful information at all. Does it still happen if you instead run `pipenv ./manage.py runserver` or do `pipenv shell` before `./manage.py runserver` ?

**Comment by shacker** [comment]
Closing issue due to no further reports or response from OP.
